# FROM python:3.11-slim

# WORKDIR /app

# # Install dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy application
# COPY publisher.py .

# # Run the publisher
# CMD ["python", "-u", "publisher.py"]